# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftStartingProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftStartingProject
  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxSwiftExt'
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'IQKeyboardManager'
  
end
